In [5]:
import numpy as np
a = np.array([[1,2,3], [5,4,6]])

def mat_is_square(mat):
    if mat.shape[0] == mat.shape[1]:
        print("Matrix is Square")
        return True
    else:
        print("Matrix is NOT Square")
        return False

mat_is_square(a)

Matrix is NOT Square


False

In [2]:
import sys
!{sys.executable} -m pip install numpy


   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   -------------------------- ------------- 8.4/12.6 MB 43.7 MB/s eta 0:00:01
   ---------------------------------------  12.6/12.6 MB 34.3 MB/s eta 0:00:01
   ---------------------------------------- 12.6/12.6 MB 29.2 MB/s eta 0:00:00


  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

[notice] A new release of pip is available: 25.0.1 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [6]:
import numpy as np

a = np.array([[1, 2, 3], [5, 4, 6]])
print(a)


[[1 2 3]
 [5 4 6]]


In [11]:
import numpy as np

a = np.array([[1, 2, 3], [5, 4, 6]])  # List of lists

def mat_is_square(mat):
    if mat.shape[0] == mat.shape[1]:
        print("Matrix is Square")
        return True
    else:
        print("Matrix is NOT Square")
        return False

mat_is_square(a)


Matrix is NOT Square


False

Its possible to create various vectors, arrays and tensors with numpy. 
import numpy as np
# Create ndarrays with numpy

In [14]:
b = np.zeros((2, 3))
c = np.ones((3, 3))
d = np.eye(3)
e = np.random.randint(0, 10, (3,3))
f = np.arange(0, 10, 2)   

print(b, c, d, e)
print(f)

[[0. 0. 0.]
 [0. 0. 0.]] [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]] [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] [[2 3 0]
 [7 1 8]
 [8 1 4]]
[0 2 4 6 8]


In [ ]:
#Step 1: Create a 6×6 matrix filled with numbers 1 to 36
import numpy as np

matrix = np.arange(1, 37).reshape(6, 6)
print("Original 6x6 Matrix:\n", matrix)

Original 6x6 Matrix:
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]


In [19]:
#Step 2: Extract a 4×4 submatrix from the center
center_submatrix = matrix[1:5, 1:5]
print("\n4x4 Center Submatrix:n\n", center_submatrix)


4x4 Center Submatrix:n
 [[ 8  9 10 11]
 [14 15 16 17]
 [20 21 22 23]
 [26 27 28 29]]


In [20]:
#Step 3: Transpose the original matrix and assign to a new variable
transposed = matrix.T
print("\nTransposed Matrix:\n", transposed)


Transposed Matrix:
 [[ 1  7 13 19 25 31]
 [ 2  8 14 20 26 32]
 [ 3  9 15 21 27 33]
 [ 4 10 16 22 28 34]
 [ 5 11 17 23 29 35]
 [ 6 12 18 24 30 36]]


In [21]:
#Step 4: Replace all even numbers in the transposed matrix with -1
transposed[transposed % 2 == 0] = -1
print(transposed)

[[ 1  7 13 19 25 31]
 [-1 -1 -1 -1 -1 -1]
 [ 3  9 15 21 27 33]
 [-1 -1 -1 -1 -1 -1]
 [ 5 11 17 23 29 35]
 [-1 -1 -1 -1 -1 -1]]


In [22]:
#Step 5: Flatten the modified matrix into a 1D array
flattened = transposed.flatten()
print(flattened)

[ 1  7 13 19 25 31 -1 -1 -1 -1 -1 -1  3  9 15 21 27 33 -1 -1 -1 -1 -1 -1
  5 11 17 23 29 35 -1 -1 -1 -1 -1 -1]


In [ ]:
#Step 6: Reshape this 1D array into a tensor of shape (2, 2, 2, 2)

tensor = flattened[:16].reshape(2,2,2,2)
print(tensor)

[[[[ 1  7]
   [13 19]]

  [[25 31]
   [-1 -1]]]


 [[[-1 -1]
   [-1 -1]]

  [[ 3  9]
   [15 21]]]]


: 

In [1]:
from numpy import array, argmin, sqrt, sum
observation = array([111.0, 188.0])
codes = array([[102.0, 203.0],
                [132.0, 193.0],
                [45.0, 155.0],
                [57.0, 173.0]])
diff = codes - observation# the broadcast happens here
dist = sqrt(sum(diff ** 2,axis =- 1))
argmin(dist)

np.int64(0)