In [5]:
import numpy as np
a = np.array([[1,2,3], [5,4,6]])

def mat_is_square(mat):
    if mat.shape[0] == mat.shape[1]:
        print("Matrix is Square")
        return True
    else:
        print("Matrix is NOT Square")
        return False

mat_is_square(a)

Matrix is NOT Square


False

In [2]:
import sys
!{sys.executable} -m pip install numpy


   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   -------------------------- ------------- 8.4/12.6 MB 43.7 MB/s eta 0:00:01
   ---------------------------------------  12.6/12.6 MB 34.3 MB/s eta 0:00:01
   ---------------------------------------- 12.6/12.6 MB 29.2 MB/s eta 0:00:00


  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

[notice] A new release of pip is available: 25.0.1 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [6]:
import numpy as np

a = np.array([[1, 2, 3], [5, 4, 6]])
print(a)


[[1 2 3]
 [5 4 6]]


In [11]:
import numpy as np

a = np.array([[1, 2, 3], [5, 4, 6]])  # List of lists

def mat_is_square(mat):
    if mat.shape[0] == mat.shape[1]:
        print("Matrix is Square")
        return True
    else:
        print("Matrix is NOT Square")
        return False

mat_is_square(a)


Matrix is NOT Square


False

Its possible to create various vectors, arrays and tensors with numpy. 
import numpy as np
# Create ndarrays with numpy

In [14]:
b = np.zeros((2, 3))
c = np.ones((3, 3))
d = np.eye(3)
e = np.random.randint(0, 10, (3,3))
f = np.arange(0, 10, 2)   

print(b, c, d, e)
print(f)

[[0. 0. 0.]
 [0. 0. 0.]] [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]] [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] [[2 3 0]
 [7 1 8]
 [8 1 4]]
[0 2 4 6 8]
